name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: composer install

  code_style:
    runs-on: ubuntu-latest
    workflows: ['composer']
    steps:
      - uses: actions/checkout@v1

      - name: install_composer
        run: composer install

      - name: code_style
        run: php ./vendor/bin/phpcs ./src --standard=PSR2 --ignore=*/vendor/*,*/Resources/*