name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: composer install
      
      - name: create-artifact
        run: zip -r project.zip ./

      - name: upload-artifact 
        uses: actions/upload-artifact@v3
        with:
          name: project-folder
          path: project.zip

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: project-folder
          path: ./

      - run: pwd

      - name: unzip-artifact
        run: unzip project.zip

      - name: code-style
        run: php ./vendor/bin/phpcs ./src --standard=PSR2 --ignore=*/vendor/*,*/Resources/*

      - name: unit-tests
        run: php ./vendor/bin/phpunit --bootstrap vendor/autoload.php ./tests/Unit/Model
