name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  composer:
    runs-on: docker://composer
    steps:
      - uses: actions/checkout@v1
      # For YAML Actions, use v2 or later
      - name: Install dependencies
        run: composer install
