name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/upload-artifact@master
      with:
        - name: bundle artifact
        - path: ./

      - name: install
        run: composer install

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: code-style
        run: php ./vendor/bin/phpcs ./src --standard=PSR2 --ignore=*/vendor/*,*/Resources/*

      - name: unit-tests
        run: php ./vendor/bin/phpunit --bootstrap vendor/autoload.php ./tests/Unit/Model
