name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  dependencies:
    runs-on: composer

    steps:
      - name: Installing dependencies
        run: composer install
