name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: composer install

  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: code-style
        run:
          - composer install
          - php ./vendor/bin/phpcs