name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # For YAML Actions, use v2 or later
      - uses: pxgamer/composer-action@master
        with:
          command: install --optimize-autoloader --prefer-dist
